### ISSUE TITLE
Show how we can extend the existing Sling Model of a component

### ISSUE THREAD

**Issue by henrykuijpers** [heervisscher/htl-examples#7]
I would love to see some examples / best practices about extending the existing Sling Model of a component.

Let's say the "Title" core component is fine the way it is, except for 1 getter that we would like to override.

It would be awesome if we can just override that 1 getter, but right now I don't see any way of doing this; Only by overriding (and copying) the existing model and then making that 1 change.

**Comment by heervisscher** [comment]
this is covered here: https://github.com/heervisscher/htl-examples/blob/master/core/src/main/java/com/adobe/examples/htl/core/models/TitleImpl.java
