### ISSUE TITLE
RequestParam direct access not working anymore

### ISSUE THREAD

**Issue by rubnig** [heervisscher/htl-examples#8]
In AEM 6.1 ${request.requestParameterMap['test'][0].toString} was working without a param 'test' in the request. HTL did all of the null checks.

in AEM 6.3 SP1 + CFP1, this isn't working anymore. Now we need to write a Sling Model to get the functionality working, when the param is missing.

I think the example should be updated with a Sling Model.

**Comment by heervisscher** [comment]
Sorry, I see your issue now. Let me look into it.

**Comment by heervisscher** [comment]
I looked into this, and indeed this is a bug. It will be fixed in AEM6.3SP2.
If you are ok with it, then I leave the sample the way it is, I added a comment on this for the bug.

**Comment by heervisscher** [comment]
https://issues.apache.org/jira/browse/SLING-7404

**Comment by rubnig** [comment]
Thanks for the update Feike!
